# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adicionar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 70, 331, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nomeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nomeLabel.setFont(font)
        self.nomeLabel.setObjectName("nomeLabel")
        self.horizontalLayout.addWidget(self.nomeLabel)
        self.nomeInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nomeInput.setObjectName("nomeInput")
        self.horizontalLayout.addWidget(self.nomeInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.numLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.numLabel.setFont(font)
        self.numLabel.setObjectName("numLabel")
        self.horizontalLayout_2.addWidget(self.numLabel)
        self.numInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.numInput.setObjectName("numInput")
        self.horizontalLayout_2.addWidget(self.numInput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.adicionarBotao = QtWidgets.QPushButton(self.centralwidget)
        self.adicionarBotao.setGeometry(QtCore.QRect(250, 290, 75, 23))
        self.adicionarBotao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionarBotao.setObjectName("adicionarBotao")
        self.listarBotao = QtWidgets.QPushButton(self.centralwidget)
        self.listarBotao.setGeometry(QtCore.QRect(440, 290, 75, 23))
        self.listarBotao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listarBotao.setObjectName("listarBotao")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nomeLabel.setText(_translate("MainWindow", "Nome"))
        self.numLabel.setText(_translate("MainWindow", "Número de Telefone"))
        self.adicionarBotao.setText(_translate("MainWindow", "Adicionar"))
        self.listarBotao.setText(_translate("MainWindow", "Listar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
